#ifndef DRONE_COMMANDS_H_FILE
#define DRONE_COMMANDS_H_FILE

enum DroneCommands {
	DRONE_COMMAND_NONE,
	DRONE_COMMAND_PAN,
	DRONE_COMMAND_LIFT,
	DRONE_COMMAND_ROTATE
};

enum PanDirection {
	PAN_DIRECTION_FORWARD,
	PAN_DIRECTION_BACKWARD,
	PAN_DIRECTION_LEFT,
	PAN_DIRECTION_RIGHT
};

enum LiftDirection {
	LIFT_DIRECTION_UP,
	LIFT_DIRECTION_DOWN
};

enum RotateDirection {
	ROTATE_DIRECTION_LEFT,
	ROTATE_DIRECTION_RIGHT
};

enum DroneMovementSpeed {
	DRONE_MOVEMENT_SPEED_NONE,
	DRONE_MOVEMENT_SPEED_LOW,
	DRONE_MOVEMENT_SPEED_MIDDLE,
	DRONE_MOVEMENT_SPEED_HIGH
};

#endif
